<?php

/**
 * PluginBlogPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBlogPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBlogPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBlogPost');
    }


    /**
     * Выборка опубликованны постов
     *
     * @param string $alias
     * @return Doctrine_Query
     */
    public function queryActive($alias = 'a')
    {
        return $this->createQuery($alias)
            ->andWhere($alias .'.is_published = 1')
            ->orderBy($alias .'.created_at DESC');
    }
}