<?php

/**
 * PluginBlogCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBlogCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBlogCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBlogComment');
    }
}