
sfYaBlogPostAdmin:
  class: sfDoctrineRouteCollection
  options:
    model:                BlogPost
    module:               sfYaBlogPostAdmin
    prefix_path:          /sfYaBlogPostAdmin
    column:               id
    with_wildcard_routes: true

